name: SpotifyCatalogAPI tests project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    name: Execute Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Unit Tests
        run: |
          mvn -Dtest=AlbumTest test
          mvn -Dtest=SongTest test
          mvn -Dtest=ArtistTest test

