name: SpotifyCatalogAPI tests

on:
  pull_request:
        branches:
          - main

jobs:
  Test:

    name: Execute Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Tests
        run: |
          mvn test -q

  TriggerDeployment:
    runs-on: ubuntu-latest
    needs: Build
    env:
      SPOTIFY_TESTING_REPO_NAME: john/SpotifyTesting
      UI_TESTING_WORKFLOW_ID: 12925485099
    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
           -H "Authorization: Bearer ${{ secrets.GITHUB_ACCESS_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d "{\"ref\": \"main\", \"inputs\": {\"browser\": \"chrome\"}}" \
           https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches